import React from "react";
import ReactDOM from "react-dom/client";
import "./index.css"; // this is the file generated by tailwind CLI
import App from "./App";

const root = ReactDOM.createRoot(document.getElementById("root"));
root.render(<App />);
